In [13]:
## Reference Video: https://www.youtube.com/watch?v=rnEVuOjjbmE&list=PLgTkNlNsy9gXoMB2-YO_Tuu94mctmu2h7&index=6
## Pyhton Marix Libraries

## Numpy
import numpy as np

## Pandas
import pandas as pd


In [103]:
A = np.array([ [1,2,3], [4, 5, 6] ])

A

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
A.T.T

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
B=np.array([ [7,8,9], [10,11,12] ])

np.dot(A, B.T)

array([[ 50,  68],
       [122, 167]])

In [73]:
C = A**2
C

array([[ 1,  4,  9],
       [16, 25, 36]])

In [75]:
D = A-1
D

array([[0, 1, 2],
       [3, 4, 5]])

In [77]:
C2 = np.array([[1,2,3], [1,2,3], [3,4,5]])
C2

array([[1, 2, 3],
       [1, 2, 3],
       [3, 4, 5]])

In [81]:
C2.diagonal()

array([1, 2, 5])

In [107]:
A=np.matrix(A)
type(A)

numpy.matrix

In [87]:
B=np.matrix(B)

In [99]:
C=np.matrix(C)

In [109]:
A

matrix([[1, 2, 3],
        [4, 5, 6]])

In [113]:
A.nonzero()

(array([0, 0, 0, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [111]:
A-B

matrix([[-6, -6, -6],
        [-6, -6, -6]])

In [115]:
A+B

matrix([[ 8, 10, 12],
        [14, 16, 18]])

In [119]:
A.dot(B.T)

matrix([[ 50,  68],
        [122, 167]])

In [121]:
A.sum()

21